# coding: utf8

BC_COMMUNITIES = [
    "Abbotsford (City)",
    "Agassiz",
    "Ahousat",
    "Ainsworth",
    "Aiyansh",
    "Albion",
    "Aldergrove (Langley Township)",
    "Alert Bay (Village)",
    "Alexandria",
    "Alexis Creek",
    "Alkali Lake",
    "Alta Lake",
    "Anahim Lake",
    "Anmore (Village)",
    "Annieville",
    "Anyox",
    "Argenta",
    "Armstrong (City)",
    "Arrandale",
    "Ashcroft (Village)",
    "Aspen Grove",
    "Atlin",
    "Attachie",
    "Australian",
    "Avola",
    "Baker Creek",
    "Baldonnel",
    "Balfour",
    "Bamberton",
    "Bamfield",
    "Barkerville",
    "Barnet",
    "Barnhartvale (Kamloops)",
    "Barnston Island",
    "Barriere",
    "Basque",
    "Bear Lake",
    "Beaton",
    "Beaverdell",
    "Bedwell Bay",
    "Bedwell Harbour",
    "Belcarra (Village)",
    "Bella Bella",
    "Bella Coola",
    "Bennett",
    "Benvoulin",
    "Beresford",
    "Bighorn",
    "Birken",
    "Black Creek",
    "Blind Bay",
    "Blubber Bay",
    "Blue River",
    "Blunden Harbour",
    "Bonaparte",
    "Boothroyd",
    "Boston Bar",
    "Boswell",
    "Botanical Beach",
    "Boundary Bay",
    "Bountiful",
    "Bowser",
    "Brackendale (Squamish)",
    "Bradner (Abbotsford)",
    "Bralorne",
    "Brentwood Bay",
    "Bridgeport",
    "Brighouse (Richmond)",
    "Brilliant",
    "Britannia Beach",
    "Brocklehurst (Kamloops)",
    "Brookmere",
    "Brunswick",
    "Buick",
    "Bull Harbour",
    "Burnaby (City)",
    "Burns Lake (Village)",
    "Burquitlam (Coquitlam)",
    "Burton",
    "Cache Creek (Village)",
    "Cameron Bar 13 (First Nations Reserve)",
    "Campbell River (City)",
    "Canal Flats (Village)",
    "Castlegar (City)",
    "Cawston",
    "Cecil Lake",
    "Cedar",
    "Cedarvale",
    "Charlie Lake",
    "Chase (VIllage)",
    "Chemainus (North Cowichan)",
    "Cherryville",
    "Chetwynd (District Municipality)",
    "Chilliwack (City)",
    "Christina Lake",
    "Clayhurst",
    "Clearbrook (Abbotsford)",
    "Clearwater",
    "Clinton (Village)",
    "Clo-oose",
    "Cloverdale (Surrey)",
    "Cluculz Lake",
    "Coal Harbour",
    "Cobble Hill",
    "Coldstream (District Municipality)",
    "Colwood (City)",
    "Comox (Town)",
    "Coombs",
    "Coquitlam (City)",
    "Courtenay (City)",
    "Cowichan 1 (First Nations Reserve)",
    "Cowichan Bay",
    "Cranberry Junction",
    "Cranbrook (City)",
    "Creston (Town)",
    "Crofton",
    "Cumberland (Village)",
    "D'Arcy",
    "Dawson Creek (City)",
    "Dease Lake",
    "Delta (City)",
    "Devine",
    "Dog Creek",
    "Duncan (City)",
    "Dunster",
    "Earls Cove",
    "Elkford (District Municipality)",
    "Enderby (City)",
    "Errington",
    "Esquimalt (District Municipality)",
    "Fanny Bay",
    "Fairmont Hot Springs",
    "Farmington",
    "Fauquier",
    "Fernie (City)",
    "Field",
    "Forest Grove",
    "Fort Fraser",
    "Fort Nelson (Town)",
    "Fort Rupert",
    "Fort St. James (District Municipality)",
    "Fort St. John (City)",
    "Fort Steele",
    "Fort Ware",
    "Fountain",
    "Francois Lake",
    "Fraser Lake",
    "Fruitvale",
    "Fulford Harbour",
    "Furry Creek",
    "Ganges",
    "Gibsons",
    "Gold Bridge",
    "Gold River",
    "Golden",
    "Goldstream",
    "Goodlow",
    "Grand Forks (City)",
    "Granisle",
    "Grasmere",
    "Greenwood",
    "Grindrod",
    "Greenville (Nisga'a Village)",
    "Groundbirch",
    "Haig",
    "Hagensborg",
    "Hanceville",
    "Harrison Hot Springs",
    "Harrison Mills",
    "Hartley Bay",
    "Hazelton",
    "Hedley",
    "Heffley Creek",
    "Heriot Bay",
    "Hixon",
    "Holberg",
    "Honeymoon Bay",
    "Hope (Town)",
    "Horsefly",
    "Houston",
    "Hudson's Hope",
    "Invermere",
    "Jackson Bay",
    "Jacksons",
    "Juskatla",
    "Kamloops (City)",
    "Keats Landing",
    "Keefers",
    "Kelowna (City)",
    "Keremeos",
    "Kimberley",
    "Kingcome Inlet",
    "Kinnaird (Castlegar)",
    "Kispiox",
    "Kitimat",
    "Lac la Hache",
    "Lac le Jeune",
    "Ladner (Delta)",
    "Ladysmith (Town)",
    "Laidlaw",
    "Lake Country (District municipality)",
    "Lake Cowichan",
    "Langdale",
    "Langford",
    "Langley (City)",
    "Langley (District Municipality)",
    "Lantzville",
    "Likely",
    "Lillooet",
    "Lions Bay",
    "Little Fort",
    "Logan Lake",
    "Lone Butte",
    "Louis Creek",
    "Lower Post",
    "Lucas",
    "Lumby",
    "Lund",
    "Lytton",
    "Mackenzie",
    "Madeira Park",
    "Malahat",
    "Mansons Landing",
    "Maple Ridge",
    "Masset",
    "Matsqui",
    "McBride",
    "McClure",
    "Merritt",
    "Merville",
    "Metchosin",
    "Mill Bay",
    "Mission (City)",
    "Moberly Lake",
    "Montney",
    "Montrose",
    "Moresby Camp",
    "Moricetown",
    "Mount Currie",
    "Moyie",
    "Nakusp",
    "Namu",
    "Nanaimo (City)",
    "Nanoose Bay",
    "Naramata",
    "Nass Camp",
    "Nelson (City)",
    "Nesikep (First Nations)",
    "New Aiyansh (Nisga'a Village)",
    "New Brighton",
    "New Denver",
    "New Westminster (City)",
    "North Pine",
    "North Vancouver (City)",
    "North Vancouver (District)",
    "N'quat'qua (First Nations)",
    "Oak Bay",
    "Ocean Falls",
    "Okanagan Falls",
    "Olalla",
    "Oliver",
    "Osoyoos",
    "Oyster River",
    "Parksville (Town)",
    "Peachland",
    "Pemberton",
    "Penticton (City)",
    "Pink Mountain",
    "Pitt Meadows",
    "Pleasant Camp",
    "Popkum",
    "Port Alberni",
    "Port Alice",
    "Port Coquitlam",
    "Port Douglas",
    "Port Edward",
    "Port Hardy",
    "Port McNeill",
    "Port Mellon",
    "Port Moody",
    "Port Renfrew",
    "Pouce Coupe",
    "Powell River",
    "Prespatou",
    "Prince George (City)",
    "Prince Rupert (City)",
    "Princeton",
    "Progress",
    "Qualicum",
    "Qualicum Beach",
    "Quathiaski Cove",
    "Quatsino",
    "Queen Charlotte City",
    "Quesnel (City)",
    "Radium Hot Springs",
    "Redroofs",
    "Revelstoke",
    "Richmond (City)",
    "River Jordan",
    "Roberts Creek",
    "Robson",
    "Rock Bay",
    "Rock Creek",
    "Rolla",
    "Rose Prairie",
    "Rosedale",
    "Rossland",
    "Rosswood",
    "Roy",
    "Royston",
    "Ruskin",
    "Saanich (City)",
    "Salmo",
    "Salmon Arm",
    "Saltair",
    "Sandspit",
    "Savona",
    "Sardis",
    "Sechelt",
    "Semahquam",
    "Seton Portage",
    "Seymour Arm",
    "Shalalth",
    "Shaw Springs",
    "Shawnigan Lake",
    "Siska",
    "Skatin (Skookumchuck Hot Springs)",
    "Skookumchuck",
    "Sicamous",
    "Sidney (City)",
    "Silverdale",
    "Silverhill",
    "Skidegate",
    "Slocan",
    "Smithers",
    "Soda Creek",
    "Sointula",
    "Sooke (City)",
    "Sparwood",
    "Spences Bridge",
    "Spuzzum",
    "Squamish",
    "Squilax (Chase)",
    "Stave Falls (and Stave Gardens)",
    "Steelhead",
    "Steveston (City of Richmond)",
    "Stewart",
    "Summerland",
    "Sunset Prairie",
    "Surrey (City)",
    "Tachie",
    "Taft",
    "Tahsis",
    "Tappen",
    "Tarry's (Castlegar District)",
    "Taylor",
    "Telegraph Cove",
    "Telegraph Creek",
    "Telkwa",
    "Terrace (City)",
    "Tête Jaune Cache",
    "Thornhill",
    "Thrums (Castlegar District)",
    "Tlell",
    "Tofino",
    "Tomslake",
    "Trail",
    "Trapp Lake",
    "Tsawwassen (Delta)",
    "Tumbler Ridge",
    "Valemount (Village)",
    "Vallican",
    "Van Anda",
    "Vancouver (City)",
    "Vanderhoof (Town)",
    "Vavenby",
    "Vernon (City)",
    "Vesuvius",
    "Victoria (City)",
    "View Royal (Town)",
    "Walnut Grove",
    "Warfield",
    "Wasa",
    "Webster's Corners",
    "Westbank",
    "West Vancouver (City)",
    "Whaletown",
    "Whonnock",
    "Whistler",
    "White Rock (City)",
    "Williams Lake",
    "Windermere",
    "Wonowon",
    "Woodfibre",
    "Woss",
    "Yahk",
    "Yale",
    "Yarrow",
    "Yennadon",
    "Ymir",
    "Youbou",
    "Zeballos",
]