# coding: utf8

BC_COMMUNITIES = sorted(['100 Mile House',
 '108 Mile House',
 'Abbotsford',
 'Agassiz',
 'Ahousat',
 'Ainsworth',
 'Aiyansh',
 'Albion',
 'Aldergrove',
 'Alert Bay',
 'Alexandria',
 'Alexis Creek',
 'Alkali Lake',
 'Alta Lake',
 'Anahim Lake',
 'Anmore',
 'Annieville',
 'Anyox',
 'Argenta',
 'Armstrong',
 'Arrandale',
 'Ashcroft',
 'Aspen Grove',
 'Atlin',
 'Attachie',
 'Australian',
 'Avola',
 'Baker Creek',
 'Baldonnel',
 'Balfour',
 'Bamberton',
 'Bamfield',
 'Barkerville',
 'Barnet',
 'Barnhartvale',
 'Barnston Island',
 'Barriere',
 'Basque',
 'Bear Lake',
 'Beaton',
 'Beaverdell',
 'Bedwell Bay',
 'Bedwell Harbour',
 'Belcarra',
 'Bella Bella',
 'Bella Coola',
 'Bennett',
 'Benvoulin',
 'Beresford',
 'Bighorn',
 'Birken',
 'Black Creek',
 'Blind Bay',
 'Blubber Bay',
 'Blue River',
 'Blunden Harbour',
 'Bonaparte',
 'Boothroyd',
 'Boston Bar',
 'Boswell',
 'Botanical Beach',
 'Boundary Bay',
 'Bountiful',
 'Bowen Island',
 'Bowser',
 'Brackendale',
 'Bradner ',
 'Bralorne',
 'Brentwood Bay',
 'Bridgeport',
 'Brighouse',
 'Brilliant',
 'Britannia Beach',
 'Brocklehurst',
 'Brookmere',
 'Brunswick',
 'Buick',
 'Bull Harbour',
 'Burnaby',
 'Burns Lake',
 'Burquitlam',
 'Burton',
 'Cache Creek',
 'Cameron Bar 13',
 'Campbell River',
 'Canal Flats',
 'Castlegar',
 'Cawston',
 'Cecil Lake',
 'Cedar',
 'Cedarvale',
 'Charlie Lake',
 'Chase',
 'Chase River',
 'Chemainus',
 'Cherryville',
 'Chetwynd',
 'Chilliwack',
 'Christina Lake',
 'Clayhurst',
 'Clearbrook',
 'Clearwater',
 'Clinton',
 'Clo-oose',
 'Cloverdale',
 'Cluculz Lake',
 'Coal Harbour',
 'Cobble Hill',
 'Coldstream',
 'Colwood',
 'Comox',
 'Coombs',
 'Coquitlam',
 'Cortes Island',
 'Courtenay',
 'Cowichan 1 ',
 'Cowichan Bay',
 'Cranberry Junction',
 'Cranbrook',
 'Crawford Bay',
 'Creston',
 'Crofton',
 'Cumberland',
 "D'Arcy",
 'Dawson Creek',
 'Delta',
 'Devine',
 'Dog Creek',
 'Duncan',
 'Duncan',
 'Dunster',
 'Earls Cove',
 'Edmonton',
 'Elkford',
 'Enderby',
 'Errington',
 'Esquimalt',
 'Fairmont Hot Springs',
 'Fanny Bay',
 'Farmington',
 'Fauquier',
 'Fernie',
 'Field',
 'Forest Grove',
 'Fort Fraser',
 'Fort Nelson',
 'Fort Rupert',
 'Fort St. James',
 'Fort St. John',
 'Fort Steele',
 'Fort Ware',
 'Fountain',
 'Francois Lake',
 'Fraser Lake',
 'Fruitvale',
 'Fulford Harbour',
 'Furry Creek',
 'Gabriola Island',
 'Galiano Island',
 'Ganges',
 'Gibsons',
 'Gold Bridge',
 'Gold River',
 'Golden',
 'Goldstream',
 'Goodlow',
 'Grand Forks',
 'Granisle',
 'Grasmere',
 'Greenville',
 'Greenwood',
 'Grindrod',
 'Groundbirch',
 'Hagensborg',
 'Haig',
 'Hanceville',
 'Harrison Hot Springs',
 'Harrison Mills',
 'Hartley Bay',
 'Hazelton',
 'Hedley',
 'Heffley Creek',
 'Heriot Bay',
 'Hixon',
 'Holberg',
 'Honeymoon Bay',
 'Hope',
 'Horsefly',
 'Houston',
 "Hudson's Hope",
 'Invermere',
 'Invermere',
 'Iskut',
 'Jackson Bay',
 'Jacksons',
 'Juskatla',
 'Kamloops',
 'Kaslo',
 'Keats Landing',
 'Keefers',
 'Kelowna',
 'Keremeos',
 'Kimberley',
 'Kingcome Inlet',
 'Kinnaird',
 'Kispiox',
 'Kitimat',
 'Kitimat',
 'Lac la Hache',
 'Lac le Jeune',
 'Ladner',
 'Ladysmith',
 'Laidlaw',
 'Lake Country',
 'Lake Cowichan',
 'Langdale',
 'Langford',
 'Langley',
 'Lantzville',
 'Lazo',
 'Likely',
 'Lillooet',
 'Lions Bay',
 'Little Fort',
 'Logan Lake',
 'Lone Butte',
 'Louis Creek',
 'Lower Post',
 'Lucas',
 'Lumby',
 'Lund',
 'Lytton',
 'Mackenzie',
 'Madeira Park',
 'Malahat',
 'Mansons Landing',
 'Maple Ridge',
 'Masset',
 'Matsqui',
 'Mayne Island',
 'McBride',
 'McClure',
 'Merritt',
 'Merville',
 'Metchosin',
 'Mill Bay',
 'Mission',
 'Moberly Lake',
 'Montney',
 'Montrose',
 'Moresby Camp',
 'Moricetown',
 'Mount Currie',
 'Moyie',
 'Nakusp',
 'Namu',
 'Nanaimo',
 'Nanoose Bay',
 'Naramata',
 'Nass Camp',
 'Nelson',
 'Nesikep',
 'New Aiyansh',
 'New Brighton',
 'New Denver',
 'New Westminster',
 'North Pine',
 'North Vancouver',
 "N'quat'qua",
 'Oak Bay',
 'Ocean Falls',
 'Okanagan Falls',
 'Olalla',
 'Oliver',
 'Osoyoos',
 'Oyster River',
 'Parksville',
 'Parson',
 'Peachland',
 'Pemberton',
 'Pender Island',
 'Penticton',
 'Pink Mountain',
 'Pitt Meadows',
 'Pleasant Camp',
 'Popkum',
 'Port Alberni',
 'Port Alice',
 'Port Coquitlam',
 'Port Douglas',
 'Port Edward',
 'Port Hardy',
 'Port McNeill',
 'Port Mellon',
 'Port Moody',
 'Port Renfrew',
 'Pouce Coupe',
 'Powell River',
 'Prespatou',
 'Prince George',
 'Prince Rupert',
 'Princeton',
 'Progress',
 'Qualicum',
 'Qualicum Beach',
 'Quathiaski Cove',
 'Quatsino',
 'Queen Charlotte City',
 'Quesnel',
 'Radium Hot Springs',
 'Redroofs',
 'Revelstoke',
 'Richmond',
 'River Jordan',
 'Roberts Creek',
 'Robson',
 'Rock Bay',
 'Rock Creek',
 'Rolla',
 'Rose Prairie',
 'Rosedale',
 'Rossland',
 'Rosswood',
 'Roy',
 'Royston',
 'Ruskin',
 'Saanich',
 'Saanichton',
 'Salmo',
 'Salmon Arm',
 'Salt Spring Island',
 'Saltair',
 'Sandspit',
 'Sardis',
 'Savona',
 'Sechelt',
 'Semahquam',
 'Seton Portage',
 'Seymour Arm',
 'Shalalth',
 'Shaw Springs',
 'Shawnigan Lake',
 'Sicamous',
 'Sidney',
 'Silverdale',
 'Silverhill',
 'Siska',
 'Skatin',
 'Skidegate',
 'Skookumchuck',
 'Slocan',
 'Smithers',
 'Soda Creek',
 'Sointula',
 'Sooke',
 'Sorrento',
 'Sparwood',
 'Spences Bridge',
 'Spuzzum',
 'Squamish',
 'Squilax',
 'Stave Falls',
 'Steelhead',
 'Steveston',
 'Stewart',
 'Summerland',
 'Sunset Prairie',
 'Surrey',
 'Tachie',
 'Taft',
 'Tahlton',
 'Tahsis',
 'Tappen',
 "Tarry's",
 'Taylor',
 'Telegraph Cove',
 'Telegraph Creek',
 'Telkwa',
 'Terrace',
 'T\xc3\xaate Jaune Cache',
 'Thornhill',
 'Thrums',
 'Tlell',
 'Tofino',
 'Tomslake',
 'Trail',
 'Trapp Lake',
 'Tsawwassen',
 'Tumbler Ridge',
 'Valemount',
 'Vallican',
 'Van Anda',
 'Vancouver',
 'Vanderhoof',
 'Vavenby',
 'Vernon',
 'Vesuvius',
 'Victoria',
 'View Royal',
 'Walnut Grove',
 'Warfield',
 'Wasa',
 "Webster's Corners",
 'West Bank',
 'West Kelowna',
 'West Vancouver',
 'Westbank',
 'Whaletown',
 'Whistler',
 'White Rock',
 'Whitehorse',
 'Whonnock',
 'Williams Lake',
 'Windermere',
 'Wonowon',
 'Woodfibre',
 'Woss',
 'Yahk',
 'Yale',
 'Yarrow',
 'Yennadon',
 'Ymir',
 'Youbou',
 'Zeballos'])
