# coding: utf8

BC_COMMUNITIES = ['100 Mile House',
 '108 Mile House',
 'Abbotsford',
 'Agassiz',
 'Aldergrove',
 'Black Creek',
 'Boston Bar',
 'Bowen Island',
 'Burnaby',
 'Burns Lake',
 'Campbell River',
 'Castlegar',
 'Chase River',
 'Chemainus',
 'Chetwynd',
 'Chilliwack',
 'Colwood',
 'Coquitlam',
 'Cortes Island',
 'Courtenay',
 'Cranbrook',
 'Crawford Bay',
 'Creston',
 'Dawson Creek',
 'Dease Lake',
 'Delta',
 'Duncan',
 'Edmonton',
 'Elkford',
 'Enderby',
 'Fauquier',
 'Fernie',
 'Fort Nelson',
 'Fort St. James',
 'Fort St. John',
 'Gabriola Island',
 'Galiano Island',
 'Golden',
 'Grand Forks',
 'Hazelton',
 'Hope',
 'Houston',
 'Invermere',
 'Iskut',
 'Kamloops',
 'Kaslo',
 'Kelowna',
 'Kimberley',
 'Kitimat',
 'Ladysmith',
 'Lake Country',
 'Langley',
 'Lantzville',
 'Lazo',
 'Lillooet',
 'Lytton',
 'Mackenzie',
 'Maple Ridge',
 'Mayne Island',
 'Merritt',
 'Mission',
 'Nakusp',
 'Nanaimo',
 'Nelson',
 'New Aiyansh',
 'New Denver',
 'New Westminster',
 'North Vancouver',
 'Parson',
 'Pender Island',
 'Penticton',
 'Port Alberni',
 'Port Coquitlam',
 'Port McNeill',
 'Port Moody',
 'Powell River',
 'Prince George',
 'Prince Rupert',
 'Princeton',
 'Quesnel',
 'Revelstoke',
 'Richmond',
 'Saanichton',
 'Salmo',
 'Salmon Arm',
 'Salt Spring Island',
 'Sechelt',
 'Sidney',
 'Smithers',
 'Sooke',
 'Sorrento',
 'Squamish',
 'Surrey',
 'Surrey-White Rock',
 'Tahlton',
 'Telegraph Creek',
 'Terrace',
 'Trail',
 'Vancouver',
 'Vernon',
 'Victoria',
 'West Bank',
 'West Kelowna',
 'West Vancouver',
 'White Rock',
 'Whitehorse',
 'Williams Lake']